### PR TITLE
Scope down unnecessary permissions

### PR DESCRIPTION
**Pull request by Almenon**
### What does this PR do?

* Unpins version for more flexibility - https://github.com/aws-ia/terraform-aws-mwaa/issues/21
* Tightens permissions for better security
* Add `secret_prefix` var one can use to grant MWAA access to secrets under a certain prefix.

### Motivation

My workplace pays me to do devops, and I can use that money to buy donuts. On a more specific level, these changes are needed for our security requirements at iSpot. The version pinning is needed to avoid conflicts.

### More
- [X] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [X] Yes, I ran `pre-commit run -a` with this PR

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by askulkarni2** [comment]
@Almenon thank you for the PR. Can you please open separate out the PR for version pinning, secrets, and scoped down permissions? Also please create issues for the secret and permissions so we can examine it closely.

**Review by vara-bonthu — COMMENTED** [review]
Thanks for the PR @Almenon ! Left few comments needs addressing other than that we are good to go.

**Comment by Almenon** [comment]
@vara-bonthu done, and good point. Thanks.

**Comment by Almenon** [comment]
@vara-bonthu following up on this, good to merge?

**Comment by vara-bonthu** [comment]
> @vara-bonthu following up on this, good to merge?

@Almenon Sorry for the delay. We are planning to test this feature and include this as a part of any upgrades required. I will merge it once its tested

**Comment by Chili-Man** [comment]
@vara-bonthu any updates on this? It's important to have the reduced permissions.

**Comment by Almenon** [comment]
Updated. I opened a new PR with conflicts resolved. See https://github.com/aws-ia/terraform-aws-mwaa/pull/49

**Pull request closed without merging**
