### PR TITLE
bump vpc module to use v5 + Add Terratest scripts

### PR DESCRIPTION
**Pull request by maiconrocha**
### What does this PR do?
bump vpc module to use v5 to fix https://github.com/hashicorp/terraform/issues/31730
adding aws_s3_bucket_ownership_controls resource to fix https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/223

Overcome deprecation warnings 

### Motivation

Errors being faced when running the basic example

### More
- [X] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I ran `pre-commit run -a` with this PR

### For Moderators
- [ ] E2E Test successfully complete before merge?

### Additional Notes

```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

mwaa_arn = "arn:aws:airflow:eu-west-1:XXXXXXXXX:environment/basic-mwaa"
mwaa_role_arn = "arn:aws:iam::XXXXXXXXX:role/mwaa-executor20230925061623422400000001"
mwaa_security_group_id = "sg-XXXXXXXXX"
mwaa_service_role_arn = "arn:aws:iam::XXXXXXXXX:role/aws-service-role/airflow.amazonaws.com/AWSServiceRoleForAmazonMWAA"
mwaa_status = "AVAILABLE"
mwaa_webserver_url = "XXXXXXXXX.eu-west-1.airflow.amazonaws.com"
```

### CODE REVIEW

**Review by vara-bonthu — APPROVED** [review]
LGTM

**Comment by maiconrocha** [comment]
I have added Terratest scripts on the last commit to close https://github.com/aws-ia/terraform-aws-mwaa/issues/5 

Test Results:
```
TestExamplesBasic 2023-09-26T09:56:33+09:30 logger.go:66: Destroy complete! Resources: 33 destroyed.
TestExamplesBasic 2023-09-26T09:56:33+09:30 logger.go:66:
```

Steps to follow:
To configure dependencies, run:

 cd test
 go mod init "<MODULE_NAME>"
 go mod tidy
Where <MODULE_NAME> is the name of your module, typically in the format github.com/<YOUR_USERNAME>/<YOUR_REPO_NAME>.

To run the tests:

cd test
go test mwaa_test.go -v -timeout 60m

**Review by vara-bonthu — APPROVED** [review]

**Comment by vara-bonthu** [comment]
@maiconrocha please resolve conflicts so that we can merge the PR

**Comment by maiconrocha** [comment]
@vara-bonthu done

**Pull request merged**
