### PR TITLE
Add support for mw1.xlarge and mw1.2xlarge environment classes

### PR DESCRIPTION
**Pull request by bjones325**
### What does this PR do?

Adds support for new MWAA environment classes:
- mw1.xlarge
- mw1.2xlarge

As released in https://aws.amazon.com/blogs/big-data/introducing-amazon-mwaa-larger-environment-sizes/

### Motivation

The release of new MWAA environment classes: https://aws.amazon.com/blogs/big-data/introducing-amazon-mwaa-larger-environment-sizes/

### More
- [ ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [x] Yes, I ran `pre-commit run -a` with this PR

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by vara-bonthu — APPROVED** [review]
LGTM

**Comment by eddie-eero** [comment]
@vara-bonthu - when is the next release? - I could use this change

**Comment by ScottFitzgerald83** [comment]
> @vara-bonthu - when is the next release? - I could use this change

+1: can we cut a new release?

**Comment by vara-bonthu** [comment]
@eddie-eero  and @ScottFitzgerald83 
Here is the new release https://github.com/aws-ia/terraform-aws-mwaa/releases/tag/v0.0.6

**Pull request merged**
