### PR TITLE
KMS policy to accept customer managed KMS keys

### PR DESCRIPTION
**Pull request by oscarmendoza123**
### What does this PR do?
Currently the policy doesn't not work with customer managed KMS keys even through the module accepts them. This ill be a no-op for existing users but will allow users with their own KMS keys to be able to use this module.

### Motivation
I have an customer managed key and noticed this was not working 

### More
- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [x] Yes, I ran `pre-commit run -a` with this PR

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by brett-petersen — APPROVED** [review]

**Review by vara-bonthu — APPROVED** [review]
LGTM

**Review by vara-bonthu — APPROVED** [review]
LGTM

**Comment by oscarmendoza123** [comment]
can someone merge

**Comment by vara-bonthu** [comment]
@oscarmendoza123 Thanks for your PR 🚀 
This has been merged now and created a new release. 
https://github.com/aws-ia/terraform-aws-mwaa/releases/tag/v0.0.5

**Pull request merged**
